
#  ██████╗ ██████╗ ██╗      ██████╗ ██████╗ ███████╗
# ██╔════╝██╔═══██╗██║     ██╔═══██╗██╔══██╗██╔════╝
# ██║     ██║   ██║██║     ██║   ██║██████╔╝███████╗
# ██║     ██║   ██║██║     ██║   ██║██╔══██╗╚════██║
# ╚██████╗╚██████╔╝███████╗╚██████╔╝██║  ██║███████║
#  ╚═════╝ ╚═════╝ ╚══════╝ ╚═════╝ ╚═╝  ╚═╝╚══════╝

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '#22272e'
    foreground: '#adbac7'
    dim_foreground: '#3c4552'
    bright_foreground: '#adbac7'
  cursor:
    text: '#1f242a'
    cursor: '#ff4b82'
  vi_mode_cursor:
    text: '#1f242a'
    cursor: '#ff4b82'
  search:
    matches:
      foreground: '#e86db2'
      background: '#3c4552'
    focused_match:
      foreground: '#1f242a'
      background: '#e86db2'
  footer_bar:
    foreground: '#e86db2'
    background: '#1f242a'
  hints:
    start:
      foreground: '#1d1f21'
      background: '#e9ff5e'
    end:
      foreground: '#e9ff5e'
      background: '#1d1f21'
  line_indicator:
    foreground: '#3c4552'
    background: '#22272e'
  selection:
    text: '#22272e'
    background: '#04f6f6'
  normal:
    black:   '#1f242a'
    red:     '#f47067'
    green:   '#2bd2b9'
    yellow:  '#f5b168'
    blue:    '#2f97ea'
    magenta: '#e86db2'
    cyan:    '#04f6f6'
    white:   '#8296aa'
  bright:
    black:   '#3c4552'
    red:     '#ff4b82'
    green:   '#00b196'
    yellow:  '#ffcc95'
    blue:    '#6fc1ff'
    magenta: '#a394cd'
    cyan:    '#87d7d7'
    white:   '#9cb6d0'
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  # indexed_colors:
  #   - { index: 16, color: '#ff00ff' }
