
# ╦╔═╔═╗╦ ╦╔╗ ╔═╗╔═╗╦═╗╔╦╗
# ╠╩╗║╣ ╚╦╝╠╩╗║ ║╠═╣╠╦╝ ║║
# ╩ ╩╚═╝ ╩ ╚═╝╚═╝╩ ╩╩╚══╩╝

[[keyboard.bindings]] # Enter tmux command mode `⌃b` + `:`
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]] # Spread panes out evenly `⌃b` + `E`
chars = "\u0002E"
key = "E"
mods = "Command"

[[keyboard.bindings]] # Toggle panes synchronisation `⌃b` + `⌃s`
chars = "\u0002\u0013"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]] # Grab and open any URL from the terminal window `⌃b` + `u`
chars = "\u0002u"
key = "U"
mods = "Command"

[[keyboard.bindings]] # Show all windows `⌃b` + `w`
chars = "\u0002w" # \x02\x77
key = "P"
mods = "Command"

[[keyboard.bindings]] # Show all sessions `⌃b` + `s`
chars = "\u0002s" # \x10
key = "P"
mods = "Command|Shift"

[[keyboard.bindings]] # Search for a pane `⌃b` + `f`
chars = "\u0002f"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]] # Save environment `⌃b` + `S`
chars = "\u0002S"
key = "S"
mods = "Command"

[[keyboard.bindings]] # Restore environment `⌃b` + `R`
chars = "\u0002R" # \x02\x52
key = "S"
mods = "Command|Shift"

[[keyboard.bindings]] # Create a vertical pane `⌃b` + `%`
chars = "\u0002%"
key = "D"
mods = "Command"

[[keyboard.bindings]] # Create a horizontal pane `⌃b` + `"`
chars = "\u0002\""
key = "D"
mods = "Command|Shift"

[[keyboard.bindings]] # Create a new window/tab
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]] # Close current pane `⌃b` + `x`
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]] # Close current window/tab `⌃b` + `&`
chars = "\u0002&"
key = "W"
mods = "Command|Shift"

[[keyboard.bindings]] # Rename current window/tab `⌃b` + `,`
chars = "\u0002,"
key = "R"
mods = "Command"

[[keyboard.bindings]] # Rename current session `⌃b` + `$`
chars = "\u0002$"
key = "R"
mods = "Command|Shift"

[[keyboard.bindings]] # Move to previous session `⌃b` + `(`
chars = "\u0002("
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]] # Move to next session `⌃b` + `)`
chars = "\u0002)"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]] # Move to previous window/tab `⌃b` + `p`
chars = "\u0002p"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]] # Move to next window/tab `⌃b` + `n`
chars = "\u0002n"
key = "L"
mods = "Command|Shift"

[[keyboard.bindings]] # Resize current pane to left `⌃b` + `H`
chars = "\u0002H"
key = "Left"
mods = "Command"

[[keyboard.bindings]] # Resize current pane to down `⌃b` + `J`
chars = "\u0002J"
key = "Down"
mods = "Command"

[[keyboard.bindings]] # Resize current pane to up `⌃b` + `K`
chars = "\u0002K"
key = "Up"
mods = "Command"

[[keyboard.bindings]] # Resize current pane to right `⌃b` + `L`
chars = "\u0002L"
key = "Right"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #1 `⌃b` + `1`
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #2 `⌃b` + `2`
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #3 `⌃b` + `3`
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #4 `⌃b` + `4`
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #5 `⌃b` + `5`
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #6 `⌃b` + `6`
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #7 `⌃b` + `7`
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #8 `⌃b` + `8`
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]] # Switch to window/tab #9 `⌃b` + `9`
chars = "\u00029"
key = "Key9"
mods = "Command"

[[keyboard.bindings]] # Start tmux copy mode
chars = "\u0002["
key = "C"
mods = "Command"

[[keyboard.bindings]] # Send `<C-q>` https://github.com/alacritty/alacritty/issues/1359
chars = "\u0011"
key = "Q"
mods = "Control"

[[keyboard.bindings]] # Send `<C-n>i` and map it `<C-i>` in VIM # https://github.com/neoclide/coc.nvim/issues/1089
chars = "\u000Ei"
key = "I"
mods = "Control"
