# ███╗   ███╗ ██████╗ ██╗   ██╗███████╗███████╗
# ████╗ ████║██╔═══██╗██║   ██║██╔════╝██╔════╝
# ██╔████╔██║██║   ██║██║   ██║███████╗█████╗
# ██║╚██╔╝██║██║   ██║██║   ██║╚════██║██╔══╝
# ██║ ╚═╝ ██║╚██████╔╝╚██████╔╝███████║███████╗
# ╚═╝     ╚═╝ ╚═════╝  ╚═════╝ ╚══════╝╚══════╝

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }
  hide_when_typing: false
