# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝

live_config_reload: true # Live config reload (changes require restart)
working_directory: None # Startup directory

window:
  opacity: 1.0
  dimensions:
    columns: 120
    lines: 26
  position:
    x: 0
    y: 0
  padding:
    x: 15
    y: 5
  decorations: buttonless
  decorations_theme_variant: None
  startup_mode: Windowed
  title: Alacritty
  dynamic_padding: false
  dynamic_title: true
  option_as_alt: None
