
# ██╗    ██╗██╗███╗   ██╗██████╗  ██████╗ ██╗    ██╗
# ██║    ██║██║████╗  ██║██╔══██╗██╔═══██╗██║    ██║
# ██║ █╗ ██║██║██╔██╗ ██║██║  ██║██║   ██║██║ █╗ ██║
# ██║███╗██║██║██║╚██╗██║██║  ██║██║   ██║██║███╗██║
# ╚███╔███╔╝██║██║ ╚████║██████╔╝╚██████╔╝╚███╔███╔╝
#  ╚══╝╚══╝ ╚═╝╚═╝  ╚═══╝╚═════╝  ╚═════╝  ╚══╝╚══╝

background_opacity: 1.0
live_config_reload: true     # Live config reload (changes require restart)
working_directory: None      # Startup directory
alt_send_esc: false          # Send ESC (\x1b) before characters when alt is pressed.

window:
  dimensions:
    columns: 120
    lines: 26
  position:
    x: 0
    y: 0
  padding:
    x: 15
    y: 5
  decorations: buttonless
  startup_mode: Windowed
  title: Alacritty
  dynamic_padding: false
  dynamic_title: true
