#define CHORDAL_HOLD
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 150

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED 12

#define SERIAL_NUMBER "Y6pdP/5WLAwE"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 4

#define RGB_MATRIX_STARTUP_SPD 60

