#define CHORDAL_HOLD
#undef RGB_MATRIX_TIMEOUT
#define RGB_MATRIX_TIMEOUT 600000

#define USB_SUSPEND_WAKEUP_DELAY 0
#define SERIAL_NUMBER "Y6pdP/40Waa4"
#define LAYER_STATE_8BIT

#define RGB_MATRIX_STARTUP_SPD 60

