# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# https://starship.rs

"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000
format = """
${custom.quote}
$all$character
"""

[custom.quote]
command = "quote" # from binaries in bin directory
when = true
format = "[$output]($style)"
style = "italic purple"

[character]
format = '$symbol '
success_symbol = '[󰘍](bold cyan)'
error_symbol = '[󰘍](bold red)'
vimcmd_symbol = '[󰘌](bold blue)'
vimcmd_replace_one_symbol = '[󰘌](bold purple)'
vimcmd_replace_symbol = '[󰘌](bold purple)'
vimcmd_visual_symbol = '[󰘌](bold yellow)'

[nix_shell]
style = 'bold blue'
symbol = '󱄅 '
format = 'via [$symbol$state( \($name\))]($style) '
impure_msg = '[impure shell](bold red)'
pure_msg = '[pure shell](bold green)'
unknown_msg = '[unknown shell](bold yellow)'

[line_break]
disabled = false

[aws]
disabled = false
force_display = false
symbol = "󰸏 "
style = "dimmed yellow"
format = '[$symbol($profile )(\($region\) )]($style)'

[battery]
format = "[$symbol$percentage]($style) "
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󱧥 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "

[[battery.display]]
threshold = 15
style = "red"

[[battery.display]]
threshold = 35
style = "yellow"

[c]
symbol = " "

[cmd_duration]
style = "dimmed purple"
format = " [󰔛 $duration]($style) "

[directory]
read_only = " 󰌾"

[docker_context]
symbol = " "

[elixir]
symbol = " "

[gcloud]
disabled = true
symbol = " "
style = "dimmed blue"
format = '[$symbol($active)( \($project\))]($style)'

[git_branch]
symbol = " "

[golang]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = "󰬷 "

[kotlin]
symbol = "󱈙 "

[memory_usage]
disabled = false
symbol = "󰍛 "

[nodejs]
symbol = " "

[package]
symbol = " "

[php]
symbol = " "

[python]
symbol = " "

[ruby]
symbol = " "

[rust]
symbol = " "
