#  █████╗ ███████╗██████╗  ██████╗ ███████╗██████╗  █████╗  ██████╗███████╗
# ██╔══██╗██╔════╝██╔══██╗██╔═══██╗██╔════╝██╔══██╗██╔══██╗██╔════╝██╔════╝
# ███████║█████╗  ██████╔╝██║   ██║███████╗██████╔╝███████║██║     █████╗
# ██╔══██║██╔══╝  ██╔══██╗██║   ██║╚════██║██╔═══╝ ██╔══██║██║     ██╔══╝
# ██║  ██║███████╗██║  ██║╚██████╔╝███████║██║     ██║  ██║╚██████╗███████╗
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝ ╚══════╝╚═╝     ╚═╝  ╚═╝ ╚═════╝╚══════╝
# https://github.com/nikitabobko/AeroSpace
# https://nikitabobko.github.io/AeroSpace/guide#config-samples

after-login-command = []
after-startup-command = ['exec-and-forget sketchybar']
start-at-login = true

# Notify SketchyBar about workspace change
exec-on-workspace-change = ["/bin/bash", "-c",
  "sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE"
]

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true
accordion-padding = 30

default-root-container-layout = "tiles" # tiles|accordion
default-root-container-orientation = "auto" # horizontal|vertical|auto
key-mapping.preset = "qwerty" # qwerty|dvorak

# Note: `outer.top` is updated through an alias that toggles SketchyBar.
[gaps]
  inner.horizontal = 24
  inner.vertical = 24
  outer.left = 20
  outer.bottom = 20
  outer.top = 46
  outer.right = 20

[exec]
  inherit-env-vars = true

[exec.env-vars]
  PATH = "/opt/homebrew/bin:/opt/homebrew/sbin:${PATH}"

# https://nikitabobko.github.io/AeroSpace/guide#on-window-detected-callback
# Print the list of running applications that appears in the Dock and may have a user interface:
# > aerospace list-apps

[[on-window-detected]]
  if.app-id = "company.thebrowser.Browser"
  run = "move-node-to-workspace 1"

[[on-window-detected]]
  if.app-id = "org.alacritty"
  run = "move-node-to-workspace 2"

[[on-window-detected]]
  if.app-id = "com.DanPristupov.Fork"
  run = "move-node-to-workspace 2"

[[on-window-detected]]
  if.app-id = "com.microsoft.VSCode"
  run = "move-node-to-workspace 3"

[[on-window-detected]]
  if.app-id = "com.tinyspeck.slackmacgap"
  run = "move-node-to-workspace 4"

[[on-window-detected]]
  if.app-id = "com.hey.app.desktop"
  run = "move-node-to-workspace 6"

[[on-window-detected]]
  if.app-id = "notion.id"
  run = "move-node-to-workspace 7"

[[on-window-detected]]
  if.app-id = "com.cron.electron"
  run = "move-node-to-workspace 8"

[[on-window-detected]]
  if.app-id = "com.anthropic.claudefordesktop"
  run = "move-node-to-workspace 9"

[mode.main.binding]
  alt-shift-ctrl-m = "mode move"
  alt-shift-ctrl-s = "mode service"
  alt-shift-ctrl-1 = "workspace 1"
  alt-shift-ctrl-2 = "workspace 2"
  alt-shift-ctrl-3 = "workspace 3"
  alt-shift-ctrl-4 = "workspace 4"
  alt-shift-ctrl-5 = "workspace 5"
  alt-shift-ctrl-6 = "workspace 6"
  alt-shift-ctrl-7 = "workspace 7"
  alt-shift-ctrl-8 = "workspace 8"
  alt-shift-ctrl-9 = "workspace 9"
  alt-shift-ctrl-period = "layout tiles horizontal vertical"
  alt-shift-ctrl-comma = "layout accordion horizontal vertical"
  alt-shift-ctrl-0 = "flatten-workspace-tree"
  alt-shift-ctrl-minus = "resize smart -100"
  alt-shift-ctrl-equal = "resize smart +100"
  alt-shift-ctrl-w = "close"
  alt-shift-ctrl-q = "close-all-windows-but-current"
  alt-shift-ctrl-d = "macos-native-minimize"
  alt-shift-ctrl-f = "fullscreen"
  alt-shift-ctrl-space = "macos-native-fullscreen"
  alt-shift-ctrl-esc = "macos-native-fullscreen off"
  alt-shift-ctrl-r = "layout horizontal vertical"
  alt-shift-ctrl-backtick = "focus-monitor next --wrap-around"
  alt-shift-ctrl-h = "focus --boundaries all-monitors-outer-frame --boundaries-action stop left"
  alt-shift-ctrl-j = "focus --boundaries all-monitors-outer-frame --boundaries-action stop down"
  alt-shift-ctrl-k = "focus --boundaries all-monitors-outer-frame --boundaries-action stop up"
  alt-shift-ctrl-l = "focus --boundaries all-monitors-outer-frame --boundaries-action stop right"
  alt-shift-ctrl-right = "workspace --wrap-around next"
  alt-shift-ctrl-left = "workspace --wrap-around prev"
  alt-shift-ctrl-tab = "workspace-back-and-forth"

[mode.move.binding]
  esc = "mode main"
  h= ["move left", "mode main"]
  j = ["move down", "mode main"]
  k = ["move up", "mode main"]
  l = ["move right", "mode main"]
  1 = ["move-node-to-workspace 1", "workspace 1", "mode main"]
  2 = ["move-node-to-workspace 2", "workspace 2", "mode main"]
  3 = ["move-node-to-workspace 3", "workspace 3", "mode main"]
  4 = ["move-node-to-workspace 4", "workspace 4", "mode main"]
  5 = ["move-node-to-workspace 5", "workspace 5", "mode main"]
  6 = ["move-node-to-workspace 6", "workspace 6", "mode main"]
  7 = ["move-node-to-workspace 7", "workspace 7", "mode main"]
  8 = ["move-node-to-workspace 8", "workspace 8", "mode main"]
  9 = ["move-node-to-workspace 9", "workspace 9", "mode main"]
  n = ["move-node-to-workspace --wrap-around next", "mode main"]
  p = ["move-node-to-workspace --wrap-around prev", "mode main"]
  backtick = ["move-workspace-to-monitor --wrap-around next", "mode main"]

[mode.service.binding]
  esc = ["reload-config", "mode main"]
  r = ["flatten-workspace-tree", "mode main"] # Reset layout
  f = ["layout floating tiling", "mode main"] # Toggle between floating and tiling layout
  backspace = ["close-all-windows-but-current", "mode main"]
