#  ██╗██████╗  █████╗ ███████╗███████╗██╗    ██╗ ██████╗ ██████╗ ██████╗
# ███║██╔══██╗██╔══██╗██╔════╝██╔════╝██║    ██║██╔═══██╗██╔══██╗██╔══██╗
# ╚██║██████╔╝███████║███████╗███████╗██║ █╗ ██║██║   ██║██████╔╝██║  ██║
#  ██║██╔═══╝ ██╔══██║╚════██║╚════██║██║███╗██║██║   ██║██╔══██╗██║  ██║
#  ██║██║     ██║  ██║███████║███████║╚███╔███╔╝╚██████╔╝██║  ██║██████╔╝
#  ╚═╝╚═╝     ╚═╝  ╚═╝╚══════╝╚══════╝ ╚══╝╚══╝  ╚═════╝ ╚═╝  ╚═╝╚═════╝
# https://developer.1password.com/docs/ssh/agent/config

# By default, all keys in your Private vault(s) are enabled.
# Ensure the SSH_AUTH_SOCK environment variable is set
# Test the result by running: ssh-add -l

[[ssh-keys]]
item = "hallaji (Ed25519)"
vault = "Personal"
account = "Riverside"

[[ssh-keys]]
item = "hallaji (RSA)"
vault = "Personal"
account = "Riverside"
