#  ██████╗ ██╗  ██╗      ██████╗  █████╗ ███████╗██╗  ██╗
# ██╔════╝ ██║  ██║      ██╔══██╗██╔══██╗██╔════╝██║  ██║
# ██║  ███╗███████║█████╗██║  ██║███████║███████╗███████║
# ██║   ██║██╔══██║╚════╝██║  ██║██╔══██║╚════██║██╔══██║
# ╚██████╔╝██║  ██║      ██████╔╝██║  ██║███████║██║  ██║
#  ╚═════╝ ╚═╝  ╚═╝      ╚═════╝ ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
# https://github.com/dlvhdr/gh-dash
# https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests

prSections:
  - title: My Open PRs
    filters: is:open author:@me
  - title: My Closed PRs
    filters: is:closed author:@me
  - title: Needs Review
    filters: is:open review-requested:@me
  - title: Drafts
    filters: is:open author:@me draft:true
  - title: Mentions
    filters: is:open mentions:@me sort:created-desc # org:cultureamp
issuesSections:
  - title: My Issues
    filters: is:open author:@me
  - title: Assigned
    filters: is:open assignee:@me
defaults:
  layout:
    prs:
      repo:
        grow: true,
        width: 10
        hidden: false
    # issues: same structure as prs
  prsLimit: 20 # global limit
  issuesLimit: 20 # global limit
  preview:
    open: true # whether to have the preview pane open by default
    width: 60 # width in columns
  refetchIntervalMinutes: 30 # will re-fetch all sections every 30 minutes
repoPaths: # configure where to locate repos when checking out PRs
  :owner/:repo: ~/code/:owner/:repo
keybindings:
pager:
  diff: less # or delta for example
confirmQuit: false # show prompt on quit or not
theme:
  ui:
    sectionsShowCount: true
    table:
      showSeparator: true
  colors:
    text:
      primary: "#adbac7"
      secondary: "#a394cd"
      inverted: "#1f242a"
      faint: "#8b97a2"
      warning: "#f5b168"
      success: "#00b196"
      error: "#ff4b82"
    background:
      selected: "#39386B"
    border:
      primary: "#39386B"
      secondary: "#39386B"
      faint: "#2B2B40"
