#  █████╗ ██╗      █████╗  ██████╗██████╗ ██╗████████╗████████╗██╗   ██╗
# ██╔══██╗██║     ██╔══██╗██╔════╝██╔══██╗██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝
# ███████║██║     ███████║██║     ██████╔╝██║   ██║      ██║    ╚████╔╝
# ██╔══██║██║     ██╔══██║██║     ██╔══██╗██║   ██║      ██║     ╚██╔╝
# ██║  ██║███████╗██║  ██║╚██████╗██║  ██║██║   ██║      ██║      ██║
# ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝ ╚═════╝╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝
# https://alacritty.org/config-alacritty.html
# https://github.com/alacritty/alacritty

[general]
import = [
  "bell.toml",
  "colors.toml",
  "cursor.toml",
  "debug.toml",
  "font.toml",
  "keyboard.toml",
  "mouse.toml",
  "scrolling.toml",
  "selection.toml",
  "terminal.toml",
  "window.toml"
]

