[bell]
color = "#f47067"

[colors.normal]
black = "#1f242a"
blue = "#2f97ea"
cyan = "#04f6f6"
green = "#2bd2b9"
magenta = "#e86db2"
red = "#f47067"
white = "#8296aa"
yellow = "#f5b168"

[colors.bright]
black = "#3c4552"
blue = "#6fc1ff"
cyan = "#87d7d7"
green = "#00b196"
magenta = "#a394cd"
red = "#ff4b82"
white = "#9cb6d0"
yellow = "#ffcc95"

[colors.cursor]
cursor = "#F4D35E"
text = "#1f242a"

[colors.footer_bar]
background = "#1f242a"
foreground = "#e86db2"

[colors.hints.end]
background = "#1d1f21"
foreground = "#e9ff5e"

[colors.hints.start]
background = "#e9ff5e"
foreground = "#1d1f21"

[colors.line_indicator]
background = "#22272e"
foreground = "#3c4552"

[colors.primary]
background = "#22272d"
bright_foreground = "#e1e4e8"
dim_foreground = "#3c4552"
foreground = "#e1e4e8"

[colors.search.focused_match]
background = "#e86db2"
foreground = "#1f242a"

[colors.search.matches]
background = "#3c4552"
foreground = "#e86db2"

[colors.selection]
background = "#04f6f6"
text = "#22272e"

[colors.vi_mode_cursor]
cursor = "#e9ff5e"
text = "#1f242a"
