[window]
decorations = "buttonless"
decorations_theme_variant = "Dark"
dynamic_padding = false
dynamic_title = true
opacity = 1.0
option_as_alt = "None"
startup_mode = "Windowed"

[window.dimensions]
columns = 120
lines = 26

[window.padding]
x = 15
y = 5

[window.position]
x = 0
y = 0
